<html>
<head>
	<link rel="stylesheet" type="text/css" href="/pebble-styles.css"/>
</head>
<body>
	<div id="logo">
		<img src="/pebble-logo.png"/>
	</div>
	<div id="messages">
		<p align="center">Your code seems to have thrown an exception:</p>
		<?foreach ($traces as $trace){?>
			<p><b><?=$trace['function']?>()</b> <?=$trace['file']?> : Line <?=$trace['line']?></p>
		<?}?>
	</div>
</body>
</html>